repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        language: system
        entry: pixi run cargo fmt
        args: [--manifest-path, rustler/Cargo.toml]
        types: [rust]
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        language: system
        entry: pixi run cargo check
        args: [--manifest-path, rustler/Cargo.toml]
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: pixi run cargo clippy
        args: [--manifest-path, rustler/Cargo.toml, --, -D, warnings]
        types: [rust]
        pass_filenames: false

      # - id: smoke-test
      #   name: smoke test
      #   language: system
      #   entry: pixi run smoke_test
      #   always_run: true
      #   pass_filenames: false
      #   stages: [pre-push]
