from datetime import datetime

from reproduce.launch import Job
from rt.data import get_mixture_path


def phase_one(
    *,
    pre_dir: str,
    eval_pre_dir: str,
    out_root: str,
    project: str,
    run_id: str,
    stage_dir: str | None,
    tokens_per_gpu: int,
    num_workers: int,
    eval_tokens_per_gpu: int,
    eval_num_workers: int,
    total_steps: int,
    early_stop_after_steps: int | None,
) -> Job:
    return Job(
        name="phase1-plurel",
        target="rt.train:main",
        args={
            "embedder": "all-MiniLM-L12-v2",
            "d_text": 384,
            "num_blocks": 12,
            "d_model": 512,
            "num_heads": 8,
            "d_ff": 2048,
            "compile": True,
            "materialize_attn_masks": True,
            "loss_fn": "huber",
            "load_ckpt_path": None,
            "db_task_list": str(get_mixture_path("plurel", "rt-plurel-train")),
            "train_splits": ["train"],
            "pre_dir": pre_dir,
            "stage_dir": stage_dir,
            "tokens_per_gpu": tokens_per_gpu,
            "num_workers": num_workers,
            "prefetch_factor": 2,
            "ctx_size_list": [512, 1024, 2048, 4096, 8192],
            "local_ctx_size_list": [128, 256, 512, 1024, 2048, 4096, 8192],
            "bfs_width_list": [8, 16, 32, 64, 128, 256],
            "prefer_latest_list": [False, True],
            "num_walks": 10_000,
            "walk_length": 20,
            "mask_prob_max": 0.0,
            "items_per_task": 100_000,
            "delta_finetune": False,
            "optimizer": "muon",
            "lr": 5e-4,
            "wd": 0.1,
            "lr_warmup_steps": 2_000,
            "lr_decay_steps": 0,
            "grad_norm_max": 1.0,
            "total_bs": 1024,
            "total_steps": total_steps,
            "early_stop_after_steps": early_stop_after_steps,
            "can_select_init_model": False,
            "swa_momentum": 0.9995,
            "seed": 0,
            "mmap_populate": True,
            "timeout_per_item": 10.0,
            "eval_freq": 1_000,
            "keep_all_ckpts": False,
            "vector_db_path": None,
            "db_cutoff": None,
            "resume_save_mins": 20.0,
            "eval_splits": ["val"],
            "eval_db_task_list": str(get_mixture_path("relbench", "forecast")),
            "eval_pre_dir": eval_pre_dir,
            "eval_tokens_per_gpu": eval_tokens_per_gpu,
            "eval_num_workers": eval_num_workers,
            "eval_prefetch_factor": 2,
            "eval_num_walks": 10_000,
            "eval_walk_length": 20,
            "eval_items_per_task": 1024,
            "eval_ctx_size_list": [8192],
            "eval_mmap_populate": True,
            "eval_shuffle_seed": 0,
            "eval_context_seed": 0,
            "eval_ensemble_size": 1,
            "eval_vector_db_path": None,
            "eval_lcs_bw_pl_grid": [(256, 32, True)],
            "run_id": run_id,
            "targets": {},
            "project": project,
            "entity": None,
            "run_name": "plurel",
            "wandb_disabled": True,
            "out_root": out_root,
        },
    )


def phase_two(
    *,
    load_ckpt_path: str,
    pre_dir: str,
    eval_pre_dir: str,
    out_root: str,
    project: str,
    run_id: str,
    stage_dir: str | None,
    tokens_per_gpu: int,
    num_workers: int,
    eval_tokens_per_gpu: int,
    eval_num_workers: int,
    total_steps: int,
    early_stop_after_steps: int | None,
) -> Job:
    return Job(
        name="phase2-the-join",
        target="rt.train:main",
        args={
            "embedder": "all-MiniLM-L12-v2",
            "d_text": 384,
            "num_blocks": 12,
            "d_model": 512,
            "num_heads": 8,
            "d_ff": 2048,
            "compile": True,
            "materialize_attn_masks": True,
            "loss_fn": "huber",
            "load_ckpt_path": load_ckpt_path,
            "db_task_list": str(get_mixture_path("the-join", "rt-j")),
            "train_splits": ["train"],
            "pre_dir": pre_dir,
            "stage_dir": stage_dir,
            "tokens_per_gpu": tokens_per_gpu,
            "num_workers": num_workers,
            "prefetch_factor": 2,
            "ctx_size_list": [512, 1024, 2048, 4096, 8192],
            "local_ctx_size_list": [128, 256, 512, 1024, 2048, 4096, 8192],
            "bfs_width_list": [8, 16, 32, 64, 128, 256],
            "prefer_latest_list": [False, True],
            "num_walks": 10_000,
            "walk_length": 20,
            "mask_prob_max": 0.0,
            "items_per_task": 100_000,
            "delta_finetune": False,
            "optimizer": "muon",
            "lr": 5e-4,
            "wd": 0.1,
            "lr_warmup_steps": 2_000,
            "lr_decay_steps": 0,
            "grad_norm_max": 1.0,
            "total_bs": 1024,
            "total_steps": total_steps,
            "early_stop_after_steps": early_stop_after_steps,
            "can_select_init_model": False,
            "swa_momentum": 0.9995,
            "seed": 0,
            "mmap_populate": True,
            "timeout_per_item": 10.0,
            "eval_freq": 1_000,
            "keep_all_ckpts": False,
            "vector_db_path": None,
            "db_cutoff": None,
            "resume_save_mins": 20.0,
            "eval_splits": ["val"],
            "eval_db_task_list": str(get_mixture_path("relbench", "forecast")),
            "eval_pre_dir": eval_pre_dir,
            "eval_tokens_per_gpu": eval_tokens_per_gpu,
            "eval_num_workers": eval_num_workers,
            "eval_prefetch_factor": 2,
            "eval_num_walks": 10_000,
            "eval_walk_length": 20,
            "eval_items_per_task": 1024,
            "eval_ctx_size_list": [8192],
            "eval_mmap_populate": True,
            "eval_shuffle_seed": 0,
            "eval_context_seed": 0,
            "eval_ensemble_size": 1,
            "eval_vector_db_path": None,
            "eval_lcs_bw_pl_grid": [(256, 32, True)],
            "run_id": run_id,
            "targets": {},
            "project": project,
            "entity": None,
            "run_name": "plurel-join",
            "wandb_disabled": True,
            "out_root": out_root,
        },
    )


def jobs(
    *,
    plurel_pre_dir: str,
    the_join_pre_dir: str,
    eval_pre_dir: str,
    out_root: str,
    project: str,
    phase_one_run_id: str,
    phase_two_run_id: str,
    phase_two_load_ckpt_path: str,
    stage_dir: str | None,
    tokens_per_gpu: int,
    num_workers: int,
    eval_tokens_per_gpu: int,
    eval_num_workers: int,
    total_steps: int,
    early_stop_after_steps: int | None,
) -> list[Job]:
    return [
        phase_one(
            pre_dir=plurel_pre_dir,
            eval_pre_dir=eval_pre_dir,
            out_root=out_root,
            project=project,
            run_id=phase_one_run_id,
            stage_dir=stage_dir,
            tokens_per_gpu=tokens_per_gpu,
            num_workers=num_workers,
            eval_tokens_per_gpu=eval_tokens_per_gpu,
            eval_num_workers=eval_num_workers,
            total_steps=total_steps,
            early_stop_after_steps=early_stop_after_steps,
        ),
        phase_two(
            load_ckpt_path=phase_two_load_ckpt_path,
            pre_dir=the_join_pre_dir,
            eval_pre_dir=eval_pre_dir,
            out_root=out_root,
            project=project,
            run_id=phase_two_run_id,
            stage_dir=stage_dir,
            tokens_per_gpu=tokens_per_gpu,
            num_workers=num_workers,
            eval_tokens_per_gpu=eval_tokens_per_gpu,
            eval_num_workers=eval_num_workers,
            total_steps=total_steps,
            early_stop_after_steps=early_stop_after_steps,
        ),
    ]


def rt_j_jobs() -> list[Job]:
    stamp = f"{datetime.now():%y-%m-%d_%H-%M-%S}"  # noqa: DTZ005
    return jobs(
        plurel_pre_dir="data/plurel-preprocessed",
        the_join_pre_dir="data/the-join-preprocessed",
        eval_pre_dir="data/relbench-preprocessed",
        out_root="~/ckpts",
        project="rt-j-pretrain",
        phase_one_run_id=f"{stamp}_phase1",
        phase_two_run_id=f"{stamp}_phase2",
        phase_two_load_ckpt_path="stanford-star/rt-plurel",
        stage_dir=None,
        tokens_per_gpu=2**17,
        num_workers=16,
        eval_tokens_per_gpu=2**17,
        eval_num_workers=3,
        total_steps=2**15 + 1,
        early_stop_after_steps=10_000,
    )


if __name__ == "__main__":
    from reproduce.launch import run_sequential

    run_sequential(rt_j_jobs())
