from datetime import datetime

from rt.data import get_mixture_path
from rt.train import main


def train(pre_dir: str, eval_pre_dir: str, out_root: str, run_id: str) -> None:
    main(
        embedder="all-MiniLM-L12-v2",
        d_text=384,
        num_blocks=12,
        d_model=512,
        num_heads=8,
        d_ff=2048,
        compile=True,
        materialize_attn_masks=True,
        loss_fn="huber",
        load_ckpt_path="stanford-star/rt-plurel",
        db_task_list=str(get_mixture_path("the-join", "rt-j")),
        train_splits=["train"],
        pre_dir=pre_dir,
        stage_dir=None,
        tokens_per_gpu=2**17,
        num_workers=16,
        prefetch_factor=2,
        ctx_size_list=[512, 1024, 2048, 4096, 8192],
        local_ctx_size_list=[128, 256, 512, 1024, 2048, 4096, 8192],
        bfs_width_list=[8, 16, 32, 64, 128, 256],
        prefer_latest_list=[False, True],
        num_walks=10_000,
        walk_length=20,
        mask_prob_max=0.0,
        items_per_task=100_000,
        delta_finetune=False,
        optimizer="muon",
        lr=5e-4,
        wd=0.1,
        lr_warmup_steps=2000,
        lr_decay_steps=0,
        grad_norm_max=1.0,
        total_bs=1024,
        total_steps=100_001,
        early_stop_after_steps=None,
        can_select_init_model=False,
        swa_momentum=0.9995,
        seed=0,
        mmap_populate=True,
        timeout_per_item=10.0,
        eval_freq=2000,
        keep_all_ckpts=True,
        vector_db_path=None,
        db_cutoff=None,
        resume_save_mins=20.0,
        eval_splits=["val"],
        eval_db_task_list=str(get_mixture_path("relbench", "forecast")),
        eval_pre_dir=eval_pre_dir,
        eval_tokens_per_gpu=2**17,
        eval_num_workers=1,
        eval_prefetch_factor=2,
        eval_num_walks=10_000,
        eval_walk_length=20,
        eval_items_per_task=1024,
        eval_ctx_size_list=[4096, 8192],
        eval_mmap_populate=True,
        eval_shuffle_seed=0,
        eval_context_seed=0,
        eval_ensemble_size=1,
        eval_vector_db_path=None,
        eval_lcs_bw_pl_grid=[(256, 32, True)],
        run_id=run_id,
        targets={},
        project="rt-train",
        entity=None,
        run_name=None,
        wandb_disabled=True,
        out_root=out_root,
    )


if __name__ == "__main__":
    train(
        pre_dir="data/the-join-preprocessed",
        eval_pre_dir="data/relbench-preprocessed",
        out_root="~/ckpts",
        run_id=f"{datetime.now():%y-%m-%d_%H-%M-%S}",  # noqa: DTZ005
    )
